# Generated by Django 4.2.3 on 2023-07-31 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='AuthorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_wpm', models.FloatField(default=0, verbose_name='Средний WPM')),
                ('best_wpm', models.FloatField(default=0, verbose_name='Лучший WPM')),
                ('best_wpm_date', models.DateField(auto_now_add=True, verbose_name='Дата лучшего WPM')),
                ('count_typed', models.IntegerField(default=0, verbose_name='Текстов напечатано')),
                ('average_accuracy', models.FloatField(default=100, verbose_name='Средний процент ошибок')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typing_trainer.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статистика по авторам',
                'verbose_name_plural': 'Статистика по авторам',
            },
        ),
        migrations.CreateModel(
            name='CategoryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_wpm', models.FloatField(default=0, verbose_name='Средний WPM')),
                ('best_wpm', models.FloatField(default=0, verbose_name='Лучший WPM')),
                ('best_wpm_date', models.DateField(auto_now_add=True, verbose_name='Дата лучшего WPM')),
                ('count_typed', models.IntegerField(default=0, verbose_name='Текстов напечатано')),
                ('average_accuracy', models.FloatField(default=100, verbose_name='Средний процент ошибок')),
            ],
            options={
                'verbose_name': 'Статистика по категориям',
                'verbose_name_plural': 'Статистика по категориям',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=7, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('average_wpm', models.FloatField(default=0, verbose_name='Средний WPM')),
                ('best_wpm', models.FloatField(default=0, verbose_name='Лучший WPM')),
                ('best_wpm_date', models.DateField(auto_now_add=True, verbose_name='Дата лучшего WPM')),
                ('count_typed', models.IntegerField(default=0, verbose_name='Текстов напечатано')),
                ('average_accuracy', models.FloatField(default=100, verbose_name='Средний процент ошибок')),
                ('author_statistic', models.ManyToManyField(through='typing_trainer.AuthorStatistics', to='typing_trainer.author')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('text', models.TextField(unique=True, verbose_name='Текст')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('displayed', models.BooleanField(default=True, verbose_name='Отображается')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='typing_trainer.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
            },
        ),
        migrations.CreateModel(
            name='TextCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.TextField(unique=True, verbose_name='CSS код')),
            ],
            options={
                'verbose_name': 'Темы',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='TextStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_wpm', models.FloatField(default=0, verbose_name='Средний WPM')),
                ('best_wpm', models.FloatField(default=0, verbose_name='Лучший WPM')),
                ('best_wpm_date', models.DateField(auto_now_add=True, verbose_name='Дата лучшего WPM')),
                ('count_typed', models.IntegerField(default=0, verbose_name='Текстов напечатано')),
                ('average_accuracy', models.FloatField(default=100, verbose_name='Средний процент ошибок')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typing_trainer.text', verbose_name='Текст')),
                ('user_statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typing_trainer.statistics', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика по текстам',
                'verbose_name_plural': 'Статистика по текстам',
            },
        ),
        migrations.AddField(
            model_name='text',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='typing_trainer.textcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='text',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='typing_trainer.language', verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='category_statistic',
            field=models.ManyToManyField(through='typing_trainer.CategoryStatistics', to='typing_trainer.textcategory'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='last_text',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_typed_text', to='typing_trainer.text', verbose_name='Последний текст'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='text_statistic',
            field=models.ManyToManyField(through='typing_trainer.TextStatistics', to='typing_trainer.text'),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('show_wpm', models.BooleanField(default=True, verbose_name='Отображать WPM')),
                ('show_percent_done', models.BooleanField(default=True, verbose_name='Отображать проценты')),
                ('show_time', models.BooleanField(default=True, verbose_name='Отображать время')),
                ('show_word_count', models.BooleanField(default=True, verbose_name='Отображать количество слов')),
                ('current_text', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='typing_trainer.text', verbose_name='Выбранный текст')),
                ('current_theme', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='typing_trainer.theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AddField(
            model_name='categorystatistics',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typing_trainer.textcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='categorystatistics',
            name='user_statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typing_trainer.statistics', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='authorstatistics',
            name='user_statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typing_trainer.statistics', verbose_name='Пользователь'),
        ),
    ]
