# Generated by Django 4.2.3 on 2023-08-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typing_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorstatistics',
            options={'ordering': ('author', '-average_wpm', '-average_accuracy', '-best_wpm', '-count_typed', 'best_wpm_date'), 'verbose_name': 'Статистика по авторам', 'verbose_name_plural': 'Статистика по авторам'},
        ),
        migrations.AlterModelOptions(
            name='categorystatistics',
            options={'ordering': ('category', '-average_wpm', '-average_accuracy', '-best_wpm', '-count_typed', 'best_wpm_date'), 'verbose_name': 'Статистика по категориям', 'verbose_name_plural': 'Статистика по категориям'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'ordering': ('-rating', '-average_wpm', '-average_accuracy', '-best_wpm', '-count_typed', 'best_wpm_date'), 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterModelOptions(
            name='textstatistics',
            options={'ordering': ('text', '-average_wpm', '-average_accuracy', '-best_wpm', '-count_typed', 'best_wpm_date'), 'verbose_name': 'Статистика по текстам', 'verbose_name_plural': 'Статистика по текстам'},
        ),
        migrations.AddField(
            model_name='settings',
            name='current_author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='typing_trainer.author', verbose_name='Выбранный автор'),
        ),
        migrations.AddField(
            model_name='settings',
            name='current_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='typing_trainer.textcategory', verbose_name='Выбранная категория'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='show_word_count',
            field=models.BooleanField(default=True, verbose_name='Отображать количество символов'),
        ),
    ]
