# Generated by Django 4.2.3 on 2023-08-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typing_trainer', '0002_alter_authorstatistics_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='show_word_count',
            new_name='show_symbols_count',
        ),
    ]
